services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root              # Root password for MySQL
      MYSQL_DATABASE: manpower               # Predefined database
    ports:
      - "3306:3306"                           # Expose MySQL port on localhost
    volumes:
      - mysql-data:/var/lib/mysql             # Volume to persist data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql                        # MySQL service name
      MYSQL_ROOT_PASSWORD: root              # Root password for MySQL
    ports:
      - "8090:80"                             # Expose phpMyAdmin on port 8080
    depends_on:
      - mysql
    restart: always

volumes:
  mysql-data:
