spring:
  application:
    name: manpower

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:manpower}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none  # Prevent overriding existing DB
    show-sql: true  # Show SQL Queries in Console (Optional)

# Swagger URL: http://localhost:8080/swagger-ui/index.html

config:
  jwt:
    issuer: demo-issuer
    leeway: 10000
    key: ${JWT_SECRET:TOKEN_SECRET}
    expirymilliseconds: 30000000
